source "https://rubygems.org"
gem "middleman-blog"
gem "middleman"
gem "susy"
gem "compass"
gem "middleman-compass"
gem "breakpoint"
gem "redcarpet"
gem "builder"
gem "sass-globbing"
gem "middleman-bibtex"
gem 'middleman-s3_sync'
gem 'middleman-sprockets'
